In [1]:
import numpy as np

In [2]:
x = np.array(42)
print(x.shape)
x.ndim

()


0

In [3]:
x = np.array([42,3,5,3,6,7])
print(x.shape)
x.ndim

(6,)


1

In [8]:
# matriz
x = np.array([[42,3,5,3,6,7],
              [66,54,5,3,6,7]])
print(x.shape)
x.ndim

(2, 6)


2

In [9]:
# tensor
x = np.array([[[42,3,5,3,6,7],
              [66,54,5,3,6,7]],
              [[42,3,5,3,6,7],
              [66,54,5,3,6,7]],
              [[42,3,5,3,6,7],
              [66,54,5,3,6,7]]])
print(x.shape)
x.ndim

(3, 2, 6)


3

Reshape

In [12]:
x = np.array([[0,1],
          [2,3],
          [4,5],
          [6,7]])
x.shape

(4, 2)

In [13]:
x.reshape(8,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [14]:
x.reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [16]:
np.transpose(x)

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [17]:
x.T

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])